# Generated by Django 5.2.6 on 2025-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestational_age_weeks', models.IntegerField()),
                ('birth_weight_kg', models.FloatField()),
                ('birth_length_cm', models.FloatField()),
                ('birth_head_circumference_cm', models.FloatField()),
                ('apgar_score', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('age_days', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('length_cm', models.FloatField()),
                ('head_circumference_cm', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('heart_rate_bpm', models.IntegerField()),
                ('respiratory_rate_bpm', models.IntegerField()),
                ('oxygen_saturation', models.FloatField()),
                ('feeding_type', models.CharField(choices=[('breast milk', 'Breast Milk'), ('formula', 'Formula'), ('mixed', 'Mixed')], max_length=20)),
                ('feeding_frequency_per_day', models.IntegerField()),
                ('urine_output_count', models.IntegerField()),
                ('stool_count', models.IntegerField()),
                ('jaundice_level_mg_dl', models.FloatField()),
                ('immunizations_done', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('reflexes_normal', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('prediction', models.CharField(max_length=50)),
                ('prediction_proba', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
